trigger: none

pool: default

stages:
    - stage: Build satege
      displayName: Build stage
      jobs:
          - job: 
            displayName: Dependencies
            steps:
                - 
