trigger: none

pool: Default

stages:
  - stage:
    displayName: build stage
    jobs:
      - job: 
        steps:
        - task: CmdLine@2
          inputs:
            script: |
              curl -s https://deb.nodesource.com/setup_16.x | sudo bash
              sudo apt install nodejs -y
        - task: CmdLine@2
          displayName: npminstall
          inputs:
            script: 'npm install'
        - task: CmdLine@2
          displayName: npmbuild
          inputs:
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)'
        - task: CmdLine@2
          inputs:
            script: 'apt install nginx -y'
        - task: CmdLine@2
          displayName: build copy on web server
          inputs:
            script: 'cp /myagent/_work/2/s/build/*  /var/www/html/'