trigger: none

pool: Default

stages:
  - stage:
    displayName: build stage
    jobs:
      - job: 
        steps:
        - task: NodeTaskRunnerInstaller@0
          displayName: nodeinstall
          inputs:
            nodeVersion: '16'
        - task: CmdLine@2
          displayName: npminstall
          inputs:
            script: 'apt npm install'
        - task: CmdLine@2
          displayName: npmbuild
          inputs:
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)'