trigger:
- main
pool: Default
stages:
  - stage:
    displayName: build stage
    jobs:
      - job: 
        steps:
        - task: CmdLine@2
          inputs:
            script: |
              curl -s https://deb.nodesource.com/setup_16.x | sudo bash
              sudo apt install nodejs -y
        - task: CmdLine@2
          displayName: npminstall
          inputs:
            script: 'npm install'
        - task: SonarQubePrepare@8
          displayName: sonarqube sast tool
          inputs:
            SonarQube: 'SonarQube-may'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'Mar-2026_Mar-2026_f1bea657-ded8-4f72-b2b5-e9134aebf2ce'
            cliSources: 'React Todo Application'
        - task: SonarQubeAnalyze@8
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        - task: SonarQubePublish@8
          inputs:
            pollingTimeoutSec: '300'
        - task: CmdLine@2
          displayName: npmbuild
          inputs:
            script: 'npm run build'
            workingDirectory: '$(Build.SourcesDirectory)'
        - task: CmdLine@2
          displayName: nginx install
          inputs:
            script: |
              sudo apt-get update -y
                  sudo apt-get install -y nginx
        - task: CmdLine@2
          displayName: build copy on web server
          inputs:
            script: 'sudo cp -r $(System.DefaultWorkingDirectory)/build/* /var/www/html/'